### ISSUE TITLE
hi，最近还在研究instant app吗？我碰到问题了

### ISSUE THREAD

**Issue by aishang5wpj** [doncc/doncc.github.io#1]
之前看了你的instant app博客，非常感谢，现在我碰到问题了。

我把instant app上传到google play上，gp却提示我资产链接没有将网站和app关联起来，我用app link assistant生成的assetlink.json，而且也上传到我的github pages上了，在app link assistant上点击测试也是通过的，但是在gp控制台却提示我没有关联。

请问你知道为啥吗？

**Comment by doncc** [comment]
不好意思才看到邮件。
是不是因为网络原因导致的，因为这个功能在国内使用确实是个问题。


原始邮件
发件人:aishang5wpjnotifications@github.com
收件人:doncc/doncc.github.iodoncc.github.io@noreply.github.com
抄送:Subscribedsubscribed@noreply.github.com
发送时间:2018年7月11日(周三) 15:14
主题:[doncc/doncc.github.io] hi，最近还在研究instant app吗？我碰到问题了 (#1)


之前看了你的instant app博客，非常感谢，现在我碰到问题了。
我把instant app上传到google play上，gp却提示我资产链接没有将网站和app关联起来，我用app link assistant生成的assetlink.json，而且也上传到我的github pages上了，在app link assistant上点击测试也是通过的，但是在gp控制台却提示我没有关联。
请问你知道为啥吗？

**Comment by doncc** [comment]
不好意思才看到邮件。 是不是因为网络原因导致的，因为这个功能在国内使用确实是个问题。

**Comment by aishang5wpj** [comment]
@doncc   后来搜了许久，发现是签名的问题，不能用自己的签名信息，要用谷歌给的https://stackoverflow.com/questions/46037099/digital-asset-link-verified-by-android-studio-but-not-pass-in-google-play-conso
